; Helper Functions
(define beginLineText (function (...input)
    (beginLine)
    (text ...input)
))

(define wholeLine (function (...input)
    (beginLine)
    (text ...input)
    (endLine)
))

(define main (function ()
    (actor SELF)
    (wholeLine "Welcome " PLAYER.name ", I've been expecting you.")

    (actor PLAYER "shocked")
    (beginLineText "You have?")
    (wait 500)
    (text " How did you know I was coming?")
    (endLine)

    (:AskQuestion)
    (actor SELF)
    (beginLineText "What is it that you wish to know?")
    (choice "Do you have powers?" (function ()
        (whatPowers)
        (moveTo main :AskQuestion)
    ))
    (choice "Do you sell stuff?" (function ()
        (doYouSell)
        (moveTo main :AskQuestion)
    ))
    (choice "Chance?" (function ()
        (chance)
        (moveTo main :AskQuestion)
    ))
    (choice "Good bye" goodBye)
    (endLine)
))

(define whatPowers (function ()
    (actor PLAYER "happy")
    (wholeLine "What kind of powers do you have?")

    (:Start)
    (choice "Can you shoot fire?" :CanShootFire?)
    (choice "Can freeze water?" :CanFreezeWater?)
    (choice "Can make lightning?" :CanMakeLightning?)
    (choice "I'm done" :Return)
    (endLine)

    (:CanShootFire?)
    (actor SELF "happy")
    (wholeLine "Most definitely I can shoot fire!")
    (jump :Start)

    (:CanFreezeWater?)
    (actor SELF)
    (wholeLine "I can, but only using a freeze.")

    (actor PLAYER)
    (wholeLine "Oh, that's not all that impressive.")
    (jump :Start)

    (:CanMakeLightning?)
    (actor SELF)
    (wholeLine "Sometimes, usually on even numbered days though.")

    (actor PLAYER)
    (wholeLine "Yea that makes sense.")
    (jump :Start)

    (:Return)
    (return)
))

(define doYouSell (function ()
    (actor PLAYER)
    (wholeLine "Do you have anything to sell?")

    (actor SELF "sad")
    (beginLineText "Unfortunately I do not at this time, if only someone could complete this quest.")
    (choice "I can quest" :ICanQuest)
    (choice "Hope you find someone" :FindSomeoneElse)
    (endLine)

    (:ICanQuest)
    (actor PLAYER "happy")
    (wholeLine "I can go on a quest for you!")
    (return)

    (:FindSomeoneElse)
    (actor PLAYER "sad")
    (wholeLine "Gee, well I hope you find someone.")
    (return)
))

(define chance (function ()
    (actor SELF)
    (beginLineText "Are you ready for some chance?\n")
    (jump (random.pick :Choice1 :Choice2 :Choice3))

    (:Choice1)
    (emotion "happy")
    (text "Random choice 1")
    (jump :AfterChoices)

    (:Choice2)
    (emotion "shocked")
    (text "Random choice 2")
    (jump :AfterChoices)

    (:Choice3)
    (emotion "sad")
    (text "Random choice 3")
    (jump :AfterChoices)

    (:AfterChoices)
    (text "\nAfter random choices")
    (endLine)
))

(define goodBye (function ()
    (actor SELF)
    (wholeLine "Thanks for coming by " PLAYER.name ", see you later")
))

(main)